-- Run as ACCOUNTADMIN/SYSADMIN. Adjust names for your enterprise.

CREATE ROLE IF NOT EXISTS AI_ETL_ADMIN;
CREATE ROLE IF NOT EXISTS AI_ETL_DEVELOPER;
CREATE ROLE IF NOT EXISTS AI_ETL_OPERATOR;
CREATE ROLE IF NOT EXISTS AI_ETL_READER;

CREATE WAREHOUSE IF NOT EXISTS ETL_WH
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS AI_WH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;
