CREATE DATABASE IF NOT EXISTS AI_ETL_DEV;

CREATE SCHEMA IF NOT EXISTS AI_ETL_DEV.CONTROL;
CREATE SCHEMA IF NOT EXISTS AI_ETL_DEV.BRONZE;
CREATE SCHEMA IF NOT EXISTS AI_ETL_DEV.SILVER;
CREATE SCHEMA IF NOT EXISTS AI_ETL_DEV.GOLD;
CREATE SCHEMA IF NOT EXISTS AI_ETL_DEV.GOV;
