USE DATABASE AI_ETL_DEV;
USE SCHEMA CONTROL;

CREATE FILE FORMAT IF NOT EXISTS FF_PARQUET
  TYPE = PARQUET
  USE_VECTORIZED_SCANNER = TRUE;

CREATE FILE FORMAT IF NOT EXISTS FF_CSV
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('NULL', 'null', '')
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE STAGE IF NOT EXISTS STG_RAW
  FILE_FORMAT = FF_PARQUET
  DIRECTORY = (ENABLE = TRUE);

CREATE STAGE IF NOT EXISTS CODE_STAGE;
CREATE STAGE IF NOT EXISTS STREAMLIT_STAGE;

-- External stage template:
-- CREATE STORAGE INTEGRATION AZURE_INT ...;
-- CREATE STAGE CONTROL.STG_RAW_EXT URL='azure://account.blob.core.windows.net/container/' STORAGE_INTEGRATION=AZURE_INT FILE_FORMAT=FF_PARQUET;
