USE DATABASE AI_ETL_DEV;
USE SCHEMA CONTROL;

CREATE TABLE IF NOT EXISTS CFG_DATASET (
    DATASET_NAME          STRING NOT NULL,
    DESCRIPTION           STRING,
    DOMAIN                STRING,
    OWNER_EMAIL           STRING,
    ENABLED               BOOLEAN DEFAULT TRUE,
    LANDING_SUBPATH       STRING NOT NULL,
    STAGE_NAME            STRING NOT NULL,
    FILE_FORMAT_NAME      STRING NOT NULL,
    FILE_TYPE             STRING DEFAULT 'PARQUET',
    TARGET_DATABASE       STRING NOT NULL,
    TARGET_SCHEMA         STRING NOT NULL,
    TARGET_TABLE          STRING NOT NULL,
    LOAD_MODE             STRING DEFAULT 'APPEND',
    PRIMARY_KEYS          VARIANT,
    PARTITION_KEYS        VARIANT,
    EXPECTED_ARRIVAL_CRON STRING,
    FRESHNESS_SLA_MINUTES NUMBER,
    SCHEMA_EVOLUTION      BOOLEAN DEFAULT TRUE,
    DQ_ENABLED            BOOLEAN DEFAULT TRUE,
    TAGS                  VARIANT,
    CREATED_AT            TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT            TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY            STRING DEFAULT CURRENT_USER(),
    UPDATED_BY            STRING DEFAULT CURRENT_USER(),
    CONSTRAINT PK_CFG_DATASET PRIMARY KEY (DATASET_NAME)
);

CREATE TABLE IF NOT EXISTS FILE_CONTROL (
    DATASET_NAME        STRING NOT NULL,
    FILE_PATH           STRING NOT NULL,
    FILE_NAME           STRING,
    FILE_SIZE_BYTES     NUMBER,
    FILE_MD5            STRING,
    FILE_LAST_MODIFIED  TIMESTAMP_LTZ,
    FILE_DATE           DATE,
    STATUS              STRING DEFAULT 'NEW',
    RETRY_COUNT         NUMBER DEFAULT 0,
    MAX_RETRIES         NUMBER DEFAULT 3,
    RUN_ID              STRING,
    LOAD_QUERY_ID       STRING,
    ERROR_MESSAGE       STRING,
    DISCOVERED_AT       TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    STARTED_AT          TIMESTAMP_LTZ,
    LOADED_AT           TIMESTAMP_LTZ,
    UPDATED_AT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_FILE_CONTROL PRIMARY KEY (DATASET_NAME, FILE_PATH)
);

CREATE TABLE IF NOT EXISTS INGEST_LOG (
    RUN_ID              STRING,
    DATASET_NAME        STRING,
    STEP_NAME           STRING,
    STATUS              STRING,
    FILES_DISCOVERED    NUMBER DEFAULT 0,
    FILES_NEW           NUMBER DEFAULT 0,
    FILES_RETRIED       NUMBER DEFAULT 0,
    FILES_LOADED        NUMBER DEFAULT 0,
    ROWS_LOADED         NUMBER DEFAULT 0,
    STARTED_AT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    ENDED_AT            TIMESTAMP_LTZ,
    DURATION_SECONDS    NUMBER,
    ERROR_MESSAGE       STRING,
    QUERY_ID            STRING,
    EXTRA_INFO          VARIANT
);

CREATE TABLE IF NOT EXISTS DDL_HISTORY (
    EVENT_ID            STRING DEFAULT UUID_STRING(),
    DATASET_NAME        STRING,
    TARGET_FQN          STRING,
    EVENT_TYPE          STRING,
    DDL_TEXT            STRING,
    STATUS              STRING,
    ERROR_MESSAGE       STRING,
    CREATED_AT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY          STRING DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS DQ_RULE (
    RULE_ID             STRING DEFAULT UUID_STRING(),
    DATASET_NAME        STRING NOT NULL,
    RULE_NAME           STRING NOT NULL,
    RULE_TYPE           STRING,
    COLUMN_NAME         STRING,
    SEVERITY            STRING DEFAULT 'MEDIUM',
    SQL_EXPRESSION      STRING NOT NULL,
    ENABLED             BOOLEAN DEFAULT TRUE,
    CREATED_AT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY          STRING DEFAULT CURRENT_USER(),
    UPDATED_AT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY          STRING DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS DQ_RESULT (
    RUN_ID              STRING,
    RULE_ID             STRING,
    DATASET_NAME        STRING,
    RULE_NAME           STRING,
    SEVERITY            STRING,
    STATUS              STRING,
    FAILED_ROW_COUNT    NUMBER,
    TOTAL_ROW_COUNT     NUMBER,
    FAILURE_RATE        FLOAT,
    RUN_TS              TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    ERROR_MESSAGE       STRING
);

CREATE TABLE IF NOT EXISTS AI_SUGGESTION_LOG (
    SUGGESTION_ID       STRING DEFAULT UUID_STRING(),
    DATASET_NAME        STRING,
    SUGGESTION_TYPE     STRING,
    MODEL_NAME          STRING,
    PROMPT_TEXT         STRING,
    RESPONSE_TEXT       STRING,
    APPROVED            BOOLEAN DEFAULT FALSE,
    APPROVED_BY         STRING,
    APPROVED_AT         TIMESTAMP_LTZ,
    CREATED_AT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY          STRING DEFAULT CURRENT_USER()
);
