USE DATABASE AI_ETL_DEV;
USE SCHEMA CONTROL;

CREATE OR REPLACE PROCEDURE SP_LOG_EVENT(
    P_RUN_ID STRING,
    P_DATASET_NAME STRING,
    P_STEP_NAME STRING,
    P_STATUS STRING,
    P_FILES_DISCOVERED NUMBER,
    P_FILES_NEW NUMBER,
    P_FILES_RETRIED NUMBER,
    P_FILES_LOADED NUMBER,
    P_ROWS_LOADED NUMBER,
    P_STARTED_AT TIMESTAMP_LTZ,
    P_ERROR_MESSAGE STRING,
    P_QUERY_ID STRING,
    P_EXTRA_INFO VARIANT
)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO INGEST_LOG (
        RUN_ID, DATASET_NAME, STEP_NAME, STATUS,
        FILES_DISCOVERED, FILES_NEW, FILES_RETRIED, FILES_LOADED, ROWS_LOADED,
        STARTED_AT, ENDED_AT, DURATION_SECONDS, ERROR_MESSAGE, QUERY_ID, EXTRA_INFO
    )
    SELECT
        P_RUN_ID, P_DATASET_NAME, P_STEP_NAME, P_STATUS,
        COALESCE(P_FILES_DISCOVERED, 0), COALESCE(P_FILES_NEW, 0), COALESCE(P_FILES_RETRIED, 0),
        COALESCE(P_FILES_LOADED, 0), COALESCE(P_ROWS_LOADED, 0),
        P_STARTED_AT, CURRENT_TIMESTAMP(), DATEDIFF('second', P_STARTED_AT, CURRENT_TIMESTAMP()),
        P_ERROR_MESSAGE, P_QUERY_ID, P_EXTRA_INFO;
    RETURN 'LOGGED';
END;
$$;

CREATE OR REPLACE PROCEDURE SP_DISCOVER_FILES(P_DAYS_BACK NUMBER)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_RUN_ID STRING DEFAULT TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISSFF3');
    V_STARTED_AT TIMESTAMP_LTZ;
    V_SQL STRING;
    V_STAGE_PATH STRING;
    V_DATASET STRING;
    V_DISCOVERED NUMBER DEFAULT 0;
    V_NEW NUMBER DEFAULT 0;
    V_TOTAL_DISCOVERED NUMBER DEFAULT 0;
    C1 CURSOR FOR
        SELECT DATASET_NAME, STAGE_NAME, LANDING_SUBPATH
        FROM CFG_DATASET
        WHERE ENABLED = TRUE;
BEGIN
    FOR R IN C1 DO
        V_STARTED_AT := CURRENT_TIMESTAMP();
        V_DATASET := R.DATASET_NAME;
        V_STAGE_PATH := '@' || R.STAGE_NAME || '/' || R.LANDING_SUBPATH;

        V_SQL := 'LIST ' || V_STAGE_PATH;
        EXECUTE IMMEDIATE V_SQL;

        CREATE OR REPLACE TEMPORARY TABLE TMP_LIST_FILES AS
        SELECT
            :V_DATASET AS DATASET_NAME,
            "name"::STRING AS FILE_PATH,
            REGEXP_SUBSTR("name"::STRING, '[^/]+$') AS FILE_NAME,
            "size"::NUMBER AS FILE_SIZE_BYTES,
            "md5"::STRING AS FILE_MD5,
            "last_modified"::TIMESTAMP_LTZ AS FILE_LAST_MODIFIED,
            TRY_TO_DATE(REGEXP_SUBSTR("name"::STRING, '[0-9]{4}/[0-9]{2}/[0-9]{2}'), 'YYYY/MM/DD') AS FILE_DATE
        FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
        WHERE "name" IS NOT NULL
          AND "last_modified"::TIMESTAMP_LTZ >= DATEADD('day', -1 * :P_DAYS_BACK, CURRENT_TIMESTAMP());

        SELECT COUNT(*) INTO :V_DISCOVERED FROM TMP_LIST_FILES;

        MERGE INTO FILE_CONTROL T
        USING TMP_LIST_FILES S
        ON T.DATASET_NAME = S.DATASET_NAME
       AND T.FILE_PATH = S.FILE_PATH
        WHEN NOT MATCHED THEN INSERT (
            DATASET_NAME, FILE_PATH, FILE_NAME, FILE_SIZE_BYTES, FILE_MD5,
            FILE_LAST_MODIFIED, FILE_DATE, STATUS, RETRY_COUNT, RUN_ID, DISCOVERED_AT, UPDATED_AT
        ) VALUES (
            S.DATASET_NAME, S.FILE_PATH, S.FILE_NAME, S.FILE_SIZE_BYTES, S.FILE_MD5,
            S.FILE_LAST_MODIFIED, S.FILE_DATE, 'NEW', 0, :V_RUN_ID, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
        )
        WHEN MATCHED AND T.STATUS IN ('FAILED_RETRYABLE') THEN UPDATE SET
            T.UPDATED_AT = CURRENT_TIMESTAMP();

        SELECT COUNT(*) INTO :V_NEW
        FROM FILE_CONTROL
        WHERE DATASET_NAME = :V_DATASET
          AND RUN_ID = :V_RUN_ID
          AND STATUS = 'NEW';

        V_TOTAL_DISCOVERED := V_TOTAL_DISCOVERED + V_DISCOVERED;

        CALL SP_LOG_EVENT(
            V_RUN_ID, V_DATASET, 'DISCOVER_FILES', 'SUCCESS',
            V_DISCOVERED, V_NEW, 0, 0, 0,
            V_STARTED_AT, NULL, LAST_QUERY_ID(), OBJECT_CONSTRUCT('stage_path', V_STAGE_PATH)
        );
    END FOR;

    RETURN OBJECT_CONSTRUCT('run_id', V_RUN_ID, 'files_discovered', V_TOTAL_DISCOVERED);
EXCEPTION
    WHEN OTHER THEN
        CALL SP_LOG_EVENT(
            V_RUN_ID, V_DATASET, 'DISCOVER_FILES', 'FAILED',
            0, 0, 0, 0, 0,
            V_STARTED_AT, SQLERRM, LAST_QUERY_ID(), OBJECT_CONSTRUCT('stage_path', V_STAGE_PATH)
        );
        RETURN OBJECT_CONSTRUCT('run_id', V_RUN_ID, 'status', 'FAILED', 'error', SQLERRM);
END;
$$;

CREATE OR REPLACE PROCEDURE SP_CREATE_OR_EVOLVE_TARGETS()
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_TARGET_FQN STRING;
    V_SQL STRING;
    V_CREATED NUMBER DEFAULT 0;
    V_DATASET STRING;
    C1 CURSOR FOR
        SELECT DATASET_NAME, TARGET_DATABASE, TARGET_SCHEMA, TARGET_TABLE
        FROM CFG_DATASET
        WHERE ENABLED = TRUE;
BEGIN
    FOR R IN C1 DO
        V_DATASET := R.DATASET_NAME;
        V_TARGET_FQN := R.TARGET_DATABASE || '.' || R.TARGET_SCHEMA || '.' || R.TARGET_TABLE;

        V_SQL := 'CREATE TABLE IF NOT EXISTS ' || V_TARGET_FQN || ' (
            RAW_RECORD VARIANT,
            SOURCE_FILE_NAME STRING,
            SOURCE_FILE_PATH STRING,
            SOURCE_FILE_LAST_MODIFIED TIMESTAMP_LTZ,
            LOAD_RUN_ID STRING,
            LOAD_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
            LOAD_DATE DATE DEFAULT CURRENT_DATE()
        )';

        EXECUTE IMMEDIATE V_SQL;
        V_CREATED := V_CREATED + 1;

        INSERT INTO DDL_HISTORY(DATASET_NAME, TARGET_FQN, EVENT_TYPE, DDL_TEXT, STATUS)
        VALUES (V_DATASET, V_TARGET_FQN, 'CREATE_IF_NOT_EXISTS', V_SQL, 'SUCCESS');
    END FOR;

    RETURN OBJECT_CONSTRUCT('targets_checked', V_CREATED, 'status', 'SUCCESS');
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO DDL_HISTORY(DATASET_NAME, TARGET_FQN, EVENT_TYPE, DDL_TEXT, STATUS, ERROR_MESSAGE)
        VALUES (V_DATASET, V_TARGET_FQN, 'CREATE_OR_EVOLVE', V_SQL, 'FAILED', SQLERRM);
        RETURN OBJECT_CONSTRUCT('status', 'FAILED', 'dataset', V_DATASET, 'error', SQLERRM);
END;
$$;

CREATE OR REPLACE PROCEDURE SP_INGEST_FILES(P_MAX_RETRIES NUMBER)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_RUN_ID STRING DEFAULT TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISSFF3');
    V_STARTED_AT TIMESTAMP_LTZ;
    V_DATASET STRING;
    V_TARGET_FQN STRING;
    V_STAGE_FILE STRING;
    V_SQL STRING;
    V_FILES_LOADED NUMBER DEFAULT 0;
    V_QUERY_ID STRING;
    C1 CURSOR FOR
        SELECT
            fc.DATASET_NAME,
            fc.FILE_PATH,
            cfg.TARGET_DATABASE || '.' || cfg.TARGET_SCHEMA || '.' || cfg.TARGET_TABLE AS TARGET_FQN,
            cfg.FILE_FORMAT_NAME
        FROM FILE_CONTROL fc
        JOIN CFG_DATASET cfg
          ON cfg.DATASET_NAME = fc.DATASET_NAME
        WHERE cfg.ENABLED = TRUE
          AND (
                fc.STATUS = 'NEW'
             OR (fc.STATUS = 'FAILED_RETRYABLE' AND fc.RETRY_COUNT < P_MAX_RETRIES)
          )
        ORDER BY fc.FILE_LAST_MODIFIED;
BEGIN
    FOR R IN C1 DO
        V_STARTED_AT := CURRENT_TIMESTAMP();
        V_DATASET := R.DATASET_NAME;
        V_TARGET_FQN := R.TARGET_FQN;
        V_STAGE_FILE := '@' || R.FILE_PATH;

        UPDATE FILE_CONTROL
        SET STATUS = 'IN_PROGRESS',
            RUN_ID = :V_RUN_ID,
            STARTED_AT = CURRENT_TIMESTAMP(),
            UPDATED_AT = CURRENT_TIMESTAMP()
        WHERE DATASET_NAME = :V_DATASET
          AND FILE_PATH = R.FILE_PATH;

        BEGIN
            V_SQL := 'INSERT INTO ' || V_TARGET_FQN || '(
                    RAW_RECORD,
                    SOURCE_FILE_NAME,
                    SOURCE_FILE_PATH,
                    SOURCE_FILE_LAST_MODIFIED,
                    LOAD_RUN_ID
                )
                SELECT
                    $1,
                    METADATA$FILENAME,
                    ''' || R.FILE_PATH || ''',
                    METADATA$FILE_LAST_MODIFIED,
                    ''' || V_RUN_ID || '''
                FROM ' || V_STAGE_FILE || ' (FILE_FORMAT => ' || R.FILE_FORMAT_NAME || ')';

            EXECUTE IMMEDIATE V_SQL;
            V_QUERY_ID := LAST_QUERY_ID();

            UPDATE FILE_CONTROL
            SET STATUS = 'LOADED',
                LOAD_QUERY_ID = :V_QUERY_ID,
                LOADED_AT = CURRENT_TIMESTAMP(),
                UPDATED_AT = CURRENT_TIMESTAMP(),
                ERROR_MESSAGE = NULL
            WHERE DATASET_NAME = :V_DATASET
              AND FILE_PATH = R.FILE_PATH;

            V_FILES_LOADED := V_FILES_LOADED + 1;

            CALL SP_LOG_EVENT(
                V_RUN_ID, V_DATASET, 'INGEST_FILE', 'SUCCESS',
                0, 0, 0, 1, 0,
                V_STARTED_AT, NULL, V_QUERY_ID,
                OBJECT_CONSTRUCT('target', V_TARGET_FQN, 'file_path', R.FILE_PATH)
            );
        EXCEPTION
            WHEN OTHER THEN
                UPDATE FILE_CONTROL
                SET STATUS = IFF(RETRY_COUNT + 1 >= :P_MAX_RETRIES, 'FAILED_FINAL', 'FAILED_RETRYABLE'),
                    RETRY_COUNT = RETRY_COUNT + 1,
                    ERROR_MESSAGE = SQLERRM,
                    UPDATED_AT = CURRENT_TIMESTAMP()
                WHERE DATASET_NAME = :V_DATASET
                  AND FILE_PATH = R.FILE_PATH;

                CALL SP_LOG_EVENT(
                    V_RUN_ID, V_DATASET, 'INGEST_FILE', 'FAILED',
                    0, 0, 0, 0, 0,
                    V_STARTED_AT, SQLERRM, LAST_QUERY_ID(),
                    OBJECT_CONSTRUCT('target', V_TARGET_FQN, 'file_path', R.FILE_PATH)
                );
        END;
    END FOR;

    RETURN OBJECT_CONSTRUCT('run_id', V_RUN_ID, 'files_loaded', V_FILES_LOADED);
END;
$$;

CREATE OR REPLACE PROCEDURE SP_RUN_DQ_RULES(P_RUN_ID STRING)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_SQL STRING;
    V_TARGET_FQN STRING;
    V_FAILED_ROWS NUMBER;
    V_TOTAL_ROWS NUMBER;
    V_STATUS STRING;
    C1 CURSOR FOR
        SELECT
            r.RULE_ID,
            r.DATASET_NAME,
            r.RULE_NAME,
            r.SEVERITY,
            r.SQL_EXPRESSION,
            cfg.TARGET_DATABASE || '.' || cfg.TARGET_SCHEMA || '.' || cfg.TARGET_TABLE AS TARGET_FQN
        FROM DQ_RULE r
        JOIN CFG_DATASET cfg ON cfg.DATASET_NAME = r.DATASET_NAME
        WHERE r.ENABLED = TRUE AND cfg.ENABLED = TRUE AND cfg.DQ_ENABLED = TRUE;
BEGIN
    FOR R IN C1 DO
        BEGIN
            V_TARGET_FQN := R.TARGET_FQN;
            V_SQL := 'SELECT COUNT(*) FROM ' || V_TARGET_FQN || ' WHERE NOT (' || R.SQL_EXPRESSION || ')';
            EXECUTE IMMEDIATE V_SQL;
            SELECT $1 INTO :V_FAILED_ROWS FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

            V_SQL := 'SELECT COUNT(*) FROM ' || V_TARGET_FQN;
            EXECUTE IMMEDIATE V_SQL;
            SELECT $1 INTO :V_TOTAL_ROWS FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

            V_STATUS := IFF(V_FAILED_ROWS = 0, 'PASSED', 'FAILED');

            INSERT INTO DQ_RESULT(RUN_ID, RULE_ID, DATASET_NAME, RULE_NAME, SEVERITY, STATUS, FAILED_ROW_COUNT, TOTAL_ROW_COUNT, FAILURE_RATE)
            VALUES(P_RUN_ID, R.RULE_ID, R.DATASET_NAME, R.RULE_NAME, R.SEVERITY, V_STATUS, V_FAILED_ROWS, V_TOTAL_ROWS, IFF(V_TOTAL_ROWS = 0, 0, V_FAILED_ROWS / V_TOTAL_ROWS));
        EXCEPTION
            WHEN OTHER THEN
                INSERT INTO DQ_RESULT(RUN_ID, RULE_ID, DATASET_NAME, RULE_NAME, SEVERITY, STATUS, ERROR_MESSAGE)
                VALUES(P_RUN_ID, R.RULE_ID, R.DATASET_NAME, R.RULE_NAME, R.SEVERITY, 'ERROR', SQLERRM);
        END;
    END FOR;
    RETURN OBJECT_CONSTRUCT('run_id', P_RUN_ID, 'status', 'DQ_COMPLETED');
END;
$$;

CREATE OR REPLACE PROCEDURE SP_AI_SUGGEST_DQ_RULES(P_DATASET_NAME STRING, P_SAMPLE_LIMIT NUMBER)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_TARGET_FQN STRING;
    V_COLUMNS_JSON STRING;
    V_PROFILE_JSON STRING;
    V_PROMPT STRING;
    V_RESPONSE STRING;
    V_MODEL STRING DEFAULT 'claude-3-5-sonnet';
    V_SQL STRING;
BEGIN
    SELECT TARGET_DATABASE || '.' || TARGET_SCHEMA || '.' || TARGET_TABLE
    INTO :V_TARGET_FQN
    FROM CFG_DATASET
    WHERE DATASET_NAME = :P_DATASET_NAME;

    SELECT TO_JSON(ARRAY_AGG(OBJECT_CONSTRUCT('column_name', COLUMN_NAME, 'data_type', DATA_TYPE)))
    INTO :V_COLUMNS_JSON
    FROM AI_ETL_DEV.INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME = :V_TARGET_FQN;

    V_SQL := 'SELECT TO_JSON(ARRAY_AGG(OBJECT_CONSTRUCT(*))) FROM (SELECT * FROM ' || V_TARGET_FQN || ' LIMIT ' || P_SAMPLE_LIMIT || ')';
    EXECUTE IMMEDIATE V_SQL;
    SELECT $1 INTO :V_PROFILE_JSON FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

    V_PROMPT := 'You are a senior data quality engineer. Suggest practical DQ rules as JSON array only. '
        || 'Each rule must include rule_name, rule_type, column_name, severity, sql_expression, business_reason. '
        || 'Dataset=' || P_DATASET_NAME || '. Columns=' || COALESCE(V_COLUMNS_JSON, '[]')
        || '. Sample rows=' || COALESCE(V_PROFILE_JSON, '[]');

    SELECT SNOWFLAKE.CORTEX.COMPLETE(:V_MODEL, :V_PROMPT) INTO :V_RESPONSE;

    INSERT INTO AI_SUGGESTION_LOG(DATASET_NAME, SUGGESTION_TYPE, MODEL_NAME, PROMPT_TEXT, RESPONSE_TEXT)
    VALUES(P_DATASET_NAME, 'DQ_RULES', V_MODEL, V_PROMPT, V_RESPONSE);

    RETURN OBJECT_CONSTRUCT('dataset_name', P_DATASET_NAME, 'target', V_TARGET_FQN, 'response', V_RESPONSE);
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO AI_SUGGESTION_LOG(DATASET_NAME, SUGGESTION_TYPE, MODEL_NAME, PROMPT_TEXT, RESPONSE_TEXT)
        VALUES(P_DATASET_NAME, 'DQ_RULES_ERROR', V_MODEL, V_PROMPT, SQLERRM);
        RETURN OBJECT_CONSTRUCT('status', 'FAILED', 'dataset_name', P_DATASET_NAME, 'error', SQLERRM);
END;
$$;

CREATE OR REPLACE PROCEDURE SP_PROCESS_CHANGED_DATASETS(P_DAYS_BACK NUMBER, P_MAX_RETRIES NUMBER)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_RUN_ID STRING DEFAULT TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISSFF3');
    V_DISCOVERY_RESULT VARIANT;
    V_DDL_RESULT VARIANT;
    V_LOAD_RESULT VARIANT;
    V_DQ_RESULT VARIANT;
BEGIN
    CALL SP_DISCOVER_FILES(P_DAYS_BACK) INTO :V_DISCOVERY_RESULT;
    CALL SP_CREATE_OR_EVOLVE_TARGETS() INTO :V_DDL_RESULT;
    CALL SP_INGEST_FILES(P_MAX_RETRIES) INTO :V_LOAD_RESULT;
    CALL SP_RUN_DQ_RULES(V_RUN_ID) INTO :V_DQ_RESULT;

    RETURN OBJECT_CONSTRUCT('run_id', V_RUN_ID, 'status', 'COMPLETED', 'discovery', V_DISCOVERY_RESULT, 'ddl', V_DDL_RESULT, 'load', V_LOAD_RESULT, 'dq', V_DQ_RESULT);
EXCEPTION
    WHEN OTHER THEN
        CALL SP_LOG_EVENT(V_RUN_ID, NULL, 'PROCESS_CHANGED_DATASETS', 'FAILED', 0, 0, 0, 0, 0, CURRENT_TIMESTAMP(), SQLERRM, LAST_QUERY_ID(), NULL);
        RETURN OBJECT_CONSTRUCT('run_id', V_RUN_ID, 'status', 'FAILED', 'error', SQLERRM);
END;
$$;

CREATE OR REPLACE PROCEDURE SP_PROCESS_ONE_DATASET(P_DATASET_NAME STRING, P_DAYS_BACK NUMBER, P_MAX_RETRIES NUMBER)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_RESULT VARIANT;
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE TMP_ENABLED_STATE AS
    SELECT DATASET_NAME, ENABLED FROM CFG_DATASET;

    UPDATE CFG_DATASET SET ENABLED = FALSE WHERE DATASET_NAME <> :P_DATASET_NAME;
    UPDATE CFG_DATASET SET ENABLED = TRUE WHERE DATASET_NAME = :P_DATASET_NAME;

    CALL SP_PROCESS_CHANGED_DATASETS(P_DAYS_BACK, P_MAX_RETRIES) INTO :V_RESULT;

    UPDATE CFG_DATASET c
    SET ENABLED = s.ENABLED
    FROM TMP_ENABLED_STATE s
    WHERE c.DATASET_NAME = s.DATASET_NAME;

    RETURN V_RESULT;
EXCEPTION
    WHEN OTHER THEN
        UPDATE CFG_DATASET c
        SET ENABLED = s.ENABLED
        FROM TMP_ENABLED_STATE s
        WHERE c.DATASET_NAME = s.DATASET_NAME;
        RETURN OBJECT_CONSTRUCT('dataset_name', P_DATASET_NAME, 'status', 'FAILED', 'error', SQLERRM);
END;
$$;
