USE DATABASE AI_ETL_DEV;
USE SCHEMA CONTROL;

CREATE OR REPLACE VIEW VW_RUN_SUMMARY AS
SELECT
    RUN_ID,
    MIN(STARTED_AT) AS STARTED_AT,
    MAX(ENDED_AT) AS ENDED_AT,
    DATEDIFF('second', MIN(STARTED_AT), MAX(ENDED_AT)) AS DURATION_SECONDS,
    COUNT(DISTINCT DATASET_NAME) AS DATASET_COUNT,
    SUM(FILES_DISCOVERED) AS FILES_DISCOVERED,
    SUM(FILES_NEW) AS FILES_NEW,
    SUM(FILES_RETRIED) AS FILES_RETRIED,
    SUM(FILES_LOADED) AS FILES_LOADED,
    SUM(ROWS_LOADED) AS ROWS_LOADED,
    IFF(COUNT_IF(STATUS = 'FAILED') > 0, 'FAILED', 'SUCCESS') AS RUN_STATUS
FROM INGEST_LOG
GROUP BY RUN_ID;

CREATE OR REPLACE VIEW VW_FAILED_FILES AS
SELECT
    fc.DATASET_NAME,
    cfg.DOMAIN,
    cfg.OWNER_EMAIL,
    fc.FILE_PATH,
    fc.STATUS,
    fc.RETRY_COUNT,
    fc.ERROR_MESSAGE,
    fc.UPDATED_AT
FROM FILE_CONTROL fc
JOIN CFG_DATASET cfg ON cfg.DATASET_NAME = fc.DATASET_NAME
WHERE fc.STATUS IN ('FAILED_RETRYABLE', 'FAILED_FINAL');

CREATE OR REPLACE VIEW VW_DATASET_HEALTH AS
SELECT
    cfg.DATASET_NAME,
    cfg.DOMAIN,
    cfg.OWNER_EMAIL,
    cfg.ENABLED,
    COUNT_IF(fc.STATUS = 'NEW') AS NEW_FILES,
    COUNT_IF(fc.STATUS = 'LOADED') AS LOADED_FILES,
    COUNT_IF(fc.STATUS = 'FAILED_RETRYABLE') AS RETRYABLE_FILES,
    COUNT_IF(fc.STATUS = 'FAILED_FINAL') AS FAILED_FINAL_FILES,
    MAX(fc.LOADED_AT) AS LAST_LOADED_AT,
    DATEDIFF('minute', MAX(fc.LOADED_AT), CURRENT_TIMESTAMP()) AS MINUTES_SINCE_LAST_LOAD,
    cfg.FRESHNESS_SLA_MINUTES,
    IFF(cfg.FRESHNESS_SLA_MINUTES IS NOT NULL
        AND MAX(fc.LOADED_AT) IS NOT NULL
        AND DATEDIFF('minute', MAX(fc.LOADED_AT), CURRENT_TIMESTAMP()) > cfg.FRESHNESS_SLA_MINUTES,
        'SLA_MISSED', 'OK') AS SLA_STATUS
FROM CFG_DATASET cfg
LEFT JOIN FILE_CONTROL fc ON cfg.DATASET_NAME = fc.DATASET_NAME
GROUP BY cfg.DATASET_NAME, cfg.DOMAIN, cfg.OWNER_EMAIL, cfg.ENABLED, cfg.FRESHNESS_SLA_MINUTES;

CREATE OR REPLACE VIEW VW_DQ_SCORECARD AS
SELECT
    DATASET_NAME,
    RULE_NAME,
    SEVERITY,
    COUNT(*) AS RUN_COUNT,
    COUNT_IF(STATUS = 'PASSED') AS PASSED_COUNT,
    COUNT_IF(STATUS = 'FAILED') AS FAILED_COUNT,
    COUNT_IF(STATUS = 'ERROR') AS ERROR_COUNT,
    MAX(RUN_TS) AS LAST_RUN_TS,
    MAX_BY(STATUS, RUN_TS) AS LAST_STATUS,
    MAX_BY(FAILURE_RATE, RUN_TS) AS LAST_FAILURE_RATE
FROM DQ_RESULT
GROUP BY DATASET_NAME, RULE_NAME, SEVERITY;
