USE DATABASE AI_ETL_DEV;
USE SCHEMA CONTROL;

CREATE OR REPLACE TASK TASK_METADATA_ETL_DAILY
  WAREHOUSE = ETL_WH
  SCHEDULE = 'USING CRON 0 6 * * * UTC'
  AS
  CALL CONTROL.SP_PROCESS_CHANGED_DATASETS(7, 3);

-- Enable only after review:
-- ALTER TASK TASK_METADATA_ETL_DAILY RESUME;
-- Manual test:
-- EXECUTE TASK TASK_METADATA_ETL_DAILY;
