USE DATABASE AI_ETL_DEV;
USE SCHEMA CONTROL;

MERGE INTO CFG_DATASET T
USING (
    SELECT
        'CUSTOMER' AS DATASET_NAME,
        'Customer master data from CRM source' AS DESCRIPTION,
        'SALES' AS DOMAIN,
        'data-engineering@example.com' AS OWNER_EMAIL,
        TRUE AS ENABLED,
        'raw/customer' AS LANDING_SUBPATH,
        'CONTROL.STG_RAW' AS STAGE_NAME,
        'CONTROL.FF_PARQUET' AS FILE_FORMAT_NAME,
        'PARQUET' AS FILE_TYPE,
        'AI_ETL_DEV' AS TARGET_DATABASE,
        'BRONZE' AS TARGET_SCHEMA,
        'CUSTOMER_RAW' AS TARGET_TABLE,
        'APPEND' AS LOAD_MODE,
        PARSE_JSON('["CUSTOMER_ID"]') AS PRIMARY_KEYS,
        PARSE_JSON('["LOAD_DATE"]') AS PARTITION_KEYS,
        '0 6 * * * UTC' AS EXPECTED_ARRIVAL_CRON,
        180 AS FRESHNESS_SLA_MINUTES,
        TRUE AS SCHEMA_EVOLUTION,
        TRUE AS DQ_ENABLED,
        PARSE_JSON('{"sensitivity":"INTERNAL","source_system":"CRM"}') AS TAGS
    UNION ALL
    SELECT
        'CLAIMS', 'Claims transactions from payer source', 'HEALTHCARE', 'data-engineering@example.com', TRUE,
        'raw/claims', 'CONTROL.STG_RAW', 'CONTROL.FF_PARQUET', 'PARQUET',
        'AI_ETL_DEV', 'BRONZE', 'CLAIMS_RAW', 'APPEND',
        PARSE_JSON('["CLAIM_ID"]'), PARSE_JSON('["LOAD_DATE"]'), '0 7 * * * UTC', 240,
        TRUE, TRUE, PARSE_JSON('{"sensitivity":"PHI","source_system":"CLAIMS_PLATFORM"}')
) S
ON T.DATASET_NAME = S.DATASET_NAME
WHEN MATCHED THEN UPDATE SET
    DESCRIPTION = S.DESCRIPTION,
    DOMAIN = S.DOMAIN,
    OWNER_EMAIL = S.OWNER_EMAIL,
    ENABLED = S.ENABLED,
    LANDING_SUBPATH = S.LANDING_SUBPATH,
    STAGE_NAME = S.STAGE_NAME,
    FILE_FORMAT_NAME = S.FILE_FORMAT_NAME,
    FILE_TYPE = S.FILE_TYPE,
    TARGET_DATABASE = S.TARGET_DATABASE,
    TARGET_SCHEMA = S.TARGET_SCHEMA,
    TARGET_TABLE = S.TARGET_TABLE,
    LOAD_MODE = S.LOAD_MODE,
    PRIMARY_KEYS = S.PRIMARY_KEYS,
    PARTITION_KEYS = S.PARTITION_KEYS,
    EXPECTED_ARRIVAL_CRON = S.EXPECTED_ARRIVAL_CRON,
    FRESHNESS_SLA_MINUTES = S.FRESHNESS_SLA_MINUTES,
    SCHEMA_EVOLUTION = S.SCHEMA_EVOLUTION,
    DQ_ENABLED = S.DQ_ENABLED,
    TAGS = S.TAGS,
    UPDATED_AT = CURRENT_TIMESTAMP(),
    UPDATED_BY = CURRENT_USER()
WHEN NOT MATCHED THEN INSERT (
    DATASET_NAME, DESCRIPTION, DOMAIN, OWNER_EMAIL, ENABLED, LANDING_SUBPATH, STAGE_NAME, FILE_FORMAT_NAME, FILE_TYPE,
    TARGET_DATABASE, TARGET_SCHEMA, TARGET_TABLE, LOAD_MODE, PRIMARY_KEYS, PARTITION_KEYS, EXPECTED_ARRIVAL_CRON,
    FRESHNESS_SLA_MINUTES, SCHEMA_EVOLUTION, DQ_ENABLED, TAGS
) VALUES (
    S.DATASET_NAME, S.DESCRIPTION, S.DOMAIN, S.OWNER_EMAIL, S.ENABLED, S.LANDING_SUBPATH, S.STAGE_NAME, S.FILE_FORMAT_NAME, S.FILE_TYPE,
    S.TARGET_DATABASE, S.TARGET_SCHEMA, S.TARGET_TABLE, S.LOAD_MODE, S.PRIMARY_KEYS, S.PARTITION_KEYS, S.EXPECTED_ARRIVAL_CRON,
    S.FRESHNESS_SLA_MINUTES, S.SCHEMA_EVOLUTION, S.DQ_ENABLED, S.TAGS
);

INSERT INTO DQ_RULE(DATASET_NAME, RULE_NAME, RULE_TYPE, COLUMN_NAME, SEVERITY, SQL_EXPRESSION)
SELECT 'CUSTOMER', 'raw_record_not_null', 'NOT_NULL', 'RAW_RECORD', 'HIGH', 'RAW_RECORD IS NOT NULL'
WHERE NOT EXISTS (SELECT 1 FROM DQ_RULE WHERE DATASET_NAME = 'CUSTOMER' AND RULE_NAME = 'raw_record_not_null');

INSERT INTO DQ_RULE(DATASET_NAME, RULE_NAME, RULE_TYPE, COLUMN_NAME, SEVERITY, SQL_EXPRESSION)
SELECT 'CLAIMS', 'raw_record_not_null', 'NOT_NULL', 'RAW_RECORD', 'HIGH', 'RAW_RECORD IS NOT NULL'
WHERE NOT EXISTS (SELECT 1 FROM DQ_RULE WHERE DATASET_NAME = 'CLAIMS' AND RULE_NAME = 'raw_record_not_null');
